---
title: "HET11 ELISpot"
author: "Yvonne Dogariu"
date: "`r Sys.Date()`"
output: html_document
---

```{r activating renv each time the project is opened}
renv::activate()

# renv::restore() # if you need to go back to locked file versions
```

# 1. Install and load libraries
```{r loading libraries}
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(scales)
library(writexl)
library(viridis)
library(lintr)
library(formatR)
library(docstring)
library(renv)
```



# 2. Set directories
```{r setting directories}
getwd()
setwd("../") # one folder up
primary_directory <- getwd()
primary_directory

setwd(primary_directory)
setwd("./data/raw") # one dot means current folder
input_directory <- getwd()
setwd(primary_directory)

setwd(primary_directory)
setwd("results")
output_directory <- getwd()
setwd(primary_directory)
```

# 3. Import excel files
```{r importing files,warning=FALSE}

read_plate_data <- function (file_path, experiment_id) {
  #' @description Read plate data from an excel with multiple sheets, where each experiment ID 
  #' has a corresponding sheet containing ELISpot SFUs and another sheet with the
  #' plate layout
  #' @param x character. file path of your excel
  #' @param y character. a vector containing the experiment ids you want to read in from the excel
    layout_var <- paste0("plate_layout_", experiment_id)
    data_var <- paste0("data_", experiment_id)

    layout_data <- read_excel(
        file_path, sheet = paste0(experiment_id, "_layout"),
        col_names = FALSE
    )
    data <- read_excel(
        file_path, sheet = paste0(experiment_id, "_data"),
        col_names = FALSE
    )

    assign(layout_var, layout_data, envir = .GlobalEnv)
    assign(data_var, data, envir = .GlobalEnv)
}

# docstring(read_plate_data) # doesn't work


setwd(input_directory)
file_path <- "ELISpot data for git.xlsx"

experiment_ids <- c("208", "274", "292")

for (id in experiment_ids) {
    read_plate_data(file_path, id)
}

setwd(input_directory)
plate_layout_timepoint <- read_excel(
    "ELISpot data for git.xlsx", sheet = "timepoint_layout",
    col_names = FALSE
)
```

## Unnecessary code to format data frames with plate layout labels
```{r, warning=FALSE}
# Define the function to update column and row names
assign_plate_layout_names <- function(df)     {
    # Check if the dataframe has 12 columns and 5 rows
    if (ncol(df) ==
        12 && nrow(df) ==
        5)
        {
        colnames(df) <- 1:12
        rownames(df) <- c("A", "B", "C", "D", "E")
        return(df)
    } else    {
        stop("The dataframe must have 12 columns and 5 rows.")
    }
}


# Create a vector with the names of your data frames
df_names <- c(
    "plate_layout_208", "plate_layout_274", "plate_layout_292", "data_208",
    "data_274", "data_292", "plate_layout_timepoint"
)

# Loop through each data frame name
for (df_name in df_names) {
    # Get the data frame by name
    df <- get(df_name)

    # Apply the function to the data frame
    df <- assign_plate_layout_names(df)

    # Assign the updated data frame back to the original variable
    assign(df_name, df)
}
```


# 4. Adjustments dataframe
```{r adjusting dataframes}
# Define the function to create well IDs based on row and column indices
assign_well_ids <- function(df) {
    if (ncol(df) == 12 && nrow(df) == 5) {
        # Create well IDs by combining row indices with column indices
        well_ids <- paste0(
            rep(LETTERS[1:5], each = 12),
            rep(1:12, times = 5)
        )

        # Reshape the dataframe to long format and add Well_ID
        df_long <- df %>%
            pivot_longer(
                cols = everything(), names_to = "Well",
                values_to = "Value"
            ) %>%
            mutate(Well_ID = well_ids)

        return(df_long)  # Return the long-format dataframe with well IDs
    } else {
        stop("The dataframe must have 12 columns and 5 rows.")
    }
}

# Define the function to convert the plate layout, counts, and annotations into
# a data frame
create_plate_data <- function(
    count_df, annotation_df, timepoint_df,
    plate_name
)     {
    # Create well IDs for count_df, annotation_df using the assign_well_ids
    # function
    count_df_long <- assign_well_ids(count_df)
    annotation_df_long <- assign_well_ids(annotation_df)
    timepoint_df_long <- assign_well_ids(timepoint_df)


    # Merge count, annotation, and cell count data frames on Well_ID
    merged_df <- count_df_long %>%
        left_join(
            annotation_df_long, by = "Well_ID",
            suffix = c("_Count", "_Annotation")
        ) %>%
        left_join(timepoint_df_long, by = "Well_ID") %>%
        mutate(Plate = plate_name)  # Add plate identifier

    # Clean up the columns to only keep the specified ones and rename them
    merged_df_cleaned <- merged_df %>%
        select(
            Well_ID, Count = Value_Count,
            Stimulation = Value_Annotation,
            Timepoint = Value, Plate
        )
    return(merged_df_cleaned)
}


annotated_208 <- create_plate_data(
    count_df = data_208, annotation_df = plate_layout_208,
    timepoint_df = plate_layout_timepoint, plate_name = "208"
)
annotated_274 <- create_plate_data(
    count_df = data_274, annotation_df = plate_layout_274,
    timepoint_df = plate_layout_timepoint, plate_name = "274"
)
annotated_292 <- create_plate_data(
    count_df = data_292, annotation_df = plate_layout_292,
    timepoint_df = plate_layout_timepoint, plate_name = "292"
)

# Combine the data for all plates
het11_elispot <- bind_rows(annotated_208, annotated_274, annotated_292)
View(het11_elispot)

# Remove NAs
het11_elispot_cleaned <- het11_elispot %>%
    filter(
        !is.na(Count) &
            !is.na(Stimulation) &
            !is.na(Plate)
    )
View(het11_elispot_cleaned)

summary(het11_elispot_cleaned)



# Make factors where necessary
het11_elispot_cleaned <- het11_elispot_cleaned %>%
  mutate(
    Well_ID = factor(Well_ID), # Convert Well_ID to factor
    Stimulation = factor(Stimulation), # Convert stimulation to factor
    Plate = factor(Plate),
    Timepoint = factor(Timepoint)
  ) # Convert Plate to factor

summary(het11_elispot_cleaned)


# Group the data by Plate and Stimulation, then calculate the average count for
# each stimulation
het11_elispot_summary <- het11_elispot_cleaned %>%
    group_by(Plate, Timepoint, Stimulation) %>%
    summarize(
        average_count = mean(Count, na.rm = TRUE),
        .groups = "drop"
    )

# Check the resulting summary data
View(het11_elispot_summary)
summary(het11_elispot_summary)


# we can intersect Plate with Timepoint so we have unique row identifiers
# Create a new column 'Unique_ID' by combining 'Plate' and 'Cell_Count' with
# '_'
het11_elispot_summary$Unique_ID <- paste(
    het11_elispot_summary$Plate, het11_elispot_summary$Timepoint,
    sep = "_"
)
# Drop the 'Plate' and 'Cell_Count' columns
het11_elispot_summary <- het11_elispot_summary %>%
    mutate(Unique_ID = factor(Unique_ID)) %>%
    select(-Plate, -Timepoint)

# Subtract background
summary(het11_elispot_summary)
het11_elispot_background_subtr_wide <- het11_elispot_summary %>%
    pivot_wider(names_from = Stimulation, values_from = average_count)

View(het11_elispot_background_subtr_wide)

# need to extract stimulations in plate layout
colnames(het11_elispot_background_subtr_wide)
# 'Unique_ID' 'DMSO' 'PHA' 'WT_S1_S2' 'BA1_S1_S2' 'NCAP'


# Calculate background subtracted data from the averaged DMSO and Spike:
het11_elispot_background_subtr_wide <- het11_elispot_background_subtr_wide %>%
    mutate(WT_S1_S2_subtr = (WT_S1_S2 - DMSO)) %>%
    mutate(BA1_S1_S2_subtr = (BA1_S1_S2 - DMSO)) %>%
    mutate(NCAP_subtr = (NCAP - DMSO)) %>%
    mutate(PHA_subtr = (PHA - DMSO))

# Make vectors for later graphs
stimulations_HET11 <- colnames(het11_elispot_background_subtr_wide)
stimulations_HET11 <- stimulations_HET11[!stimulations_HET11 %in% c("Unique_ID")]

stimulations_subtracted <- grep(
    "_subtr", stimulations_HET11, ignore.case = FALSE,
    value = TRUE
)

stimulations_subtracted_wo_posctrl <- stimulations_subtracted[!stimulations_subtracted %in%
    c("PHA_subtr")]
stimulations_subtracted_wo_posctrl %in% stimulations_subtracted


# Replace negative values and 0s with llod
llod <- (1/3)/2  # 1 spot per 3 DMSO replicates and then take half of that
het11_elispot_background_subtr_wide[stimulations_subtracted][het11_elispot_background_subtr_wide[stimulations_subtracted] <=
    0] <- llod

# Make the data frame in long format
het11_elispot_background_subtr_long <- het11_elispot_background_subtr_wide %>%
    gather(key = Stimulation, value = Counts, all_of(stimulations_HET11))

View(het11_elispot_background_subtr_long)

# Remove NA rows
het11_elispot_background_subtr_long_cleaned <- na.omit(het11_elispot_background_subtr_long)  
# this removes rows that contain NA values in any of the columns
View(het11_elispot_background_subtr_long_cleaned)

# We want to break up the UNique ID column in relevant columns for analysis
unique(het11_elispot_background_subtr_long_cleaned$Unique_ID)

het11_elispot_background_subtr_long_cleaned <- het11_elispot_background_subtr_long_cleaned %>%
    separate(
        Unique_ID, into = c("Donor_ID", "Timepoint"),
        sep = "_"
    )
View(het11_elispot_background_subtr_long_cleaned)


```

## Code to save data frames
```{r saving dataframes outside R}
setwd(input_directory)
setwd("../")
setwd("temp")

# all plates in one file without any manipulation (no average of replicates)
write_xlsx(het11_elispot_cleaned, 
           path = "01_HET11_ELISpot_cleaned.xlsx")

# wide data background subtracted no llod applied
write_xlsx(het11_elispot_background_subtr_wide, 
           path = "02_HET11_ELISpot_BGsubtracted_averaged_cleaned_no_llod_wide.xlsx")


setwd(input_directory)
setwd("../")
setwd("processed")

# final dataset for plotting
write_xlsx(het11_elispot_background_subtr_long_cleaned, 
           path = "03_HET11_ELISpot_BGsubtracted_averaged_cleaned_w_llod_applied_long.xlsx")

# TODO: it would be better if i could keep the dataframe saving in the loop, 
# but make the name unique each time by pasting a timestamp on it
```


# 5. Plot data
```{r plotting}

df <- het11_elispot_background_subtr_long_cleaned[het11_elispot_background_subtr_long_cleaned$Stimulation %in%
    stimulations_subtracted, ]

df <- df %>%
    mutate(
        Stimulation = factor(
            Stimulation,
            levels = stimulations_subtracted
        )
    ) %>%
    mutate(
        Timepoint = factor(Timepoint, levels = c("Tc", "B0", "B1", "MB444")
        )
    )
View(df)

# Create additional output folder
setwd(output_directory)
dir.create("figures", showWarnings = FALSE)
setwd("figures")


plot <- ggplot(df, aes(x = Timepoint, y = 5 * Counts)) +
    geom_boxplot(alpha = 0.3, outlier.shape = NA) +
    geom_point(
        aes(shape = Donor_ID, col = Timepoint),
        size = 3, alpha = 0.9
    ) +
    geom_line(
        aes(group = Donor_ID),
        alpha = 0.3, colour = "darkgrey"
    ) +
    geom_hline(
        yintercept = 5 * llod, color = "grey0", linetype = "dashed",
        size = 0.8
    ) +
    facet_wrap(~Stimulation, scales = "free_y", ncol = 4) +

scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
) +
    scale_color_viridis_d(option = "D", end = 1) +

theme_bw(base_size = 14) +
    theme(
        axis.text.x = element_text(
            angle = 0, hjust = 0.5, size = 12,
            face = "bold"
        ),
        axis.title = element_text(size = 14, face = "bold"),
        strip.text = element_text(size = 14, face = "bold"),
        legend.title = element_text(size = 13),
        legend.text = element_text(size = 11),
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_blank()
    ) +
    labs(
        y = "IFNg SFUs per 1 million PBMCs", x = "Timepoint",
        color = "Timepoint", shape = "Donor ID",
        title = NULL
    )

ggsave(
    filename = "HET11_synth_wrapped_by_stim_BGsubtracted_log.png", plot = plot,
    scale = 1, width = 45, height = 23, units = "cm"
)
```
